services:
  postgres:
    image: postgres:16.4-alpine3.20
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "Test123"
    volumes:
      - ./data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:8.11.0
    container_name: pgadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@server.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    depends_on:
      - postgres